name: gpytorch_MKL
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pyyaml
  - setuptools
  - cmake
  - cffi
  - typing
  - seaborn
  - astropy
  - astroquery
  - celerite
  - bokeh
  - uncertainties
  - pip
  - pytorch
  - torchvision
  - cython
  - scipy
  - jupyter
  - ipython
  - matplotlib
  - pandas
  - pytest
  - scikit-learn
  - six
  - future
  - nbsphinx
  - ipykernel
  - black
  - twine
  - sphinx_rtd_theme
  - m2r
  - flake8
  - flake8-print
  - lightkurve
  - pip:
    - pyro-ppl
    - pykeops
    - emcee
    - sphinx==1.7.9 #for building PyTorch docs
    - -e git+git://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme
    - sphinxcontrib.katex
